#!/bin/sh
ALICE_DIR=/usr/lib/erlang/lib/alice

cd $ALICE_DIR

make

if [ ! -f ebin/rest_app.boot ]; then
    make boot
fi

erl -pa $ALICE_DIR/ebin -pa $ALICE_DIR/deps/*/ebin -s reloader -boot alice $*



